name: portfolio
description: This is my personal portfolion, I am creating and updating threw my whole game design and game development journey. 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.1.4 <4.0.0'


# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.1
  mailto: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Images and other assets
  assets:
    - assets/images/portfolio/logo.png
    - assets/cv/curriculum_vitae-Pascal Dohle.pdf
    - assets/images/portfolio/sketchofme.png

  # Custom Fonts
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
          
    - family: Minion
      fonts:
        - asset: assets/fonts/minion/Minion-Regular.otf
        - asset: assets/fonts/minion/Minion-Bold.otf
        - asset: assets/fonts/minion/Minion-It.otf
    - family: Myriad
      fonts:
        - asset: assets/fonts/myriad/Myriad-Pro-Black.otf
        - asset: assets/fonts/myriad/Myriad-Pro-Black-Italic.otf
        - asset: assets/fonts/myriad/Myriad-Pro-Bold-Condensed-Italic.ttf
